spring:
  jpa:
    h2:
      console:
        enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
        path: /h2-console  # H2 Console의 Path
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      show_sql: true
      format_sql: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: