name: app_boot_test
on: [pull_request]

jobs:
  boot:

    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Set up JDK 17
        uses: actions/setup-java@master
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew :wanderlog-api:build

      - name: App boot
        run: ./healthcheck.sh


