name: 'Auto Assign'
on:
  pull_request_target:
    types: [opened, ready_for_review]

jobs:
  add-assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.4
        with:
          configuration-path: '.github/auto_assign_pr_config.yml'
          repo-token: '${{ secrets.github_token }}'
